### PR TITLE
Change UUID to use [UIDevice identifierForVendor] on iOS

### PR DESCRIPTION
**Pull request by tenfef**
instead of generating a UUID, just use the unique identifierForVendor for device which is valid since iOS 6.0
Since Cordova dropped support for iOS 5, I think this is a safe change.

### CODE REVIEW

**Comment by jcesarmobile** [comment]
First of all, an issue is needed before merging this, create a new one here http://issues.cordova.io/ and use the identifier you get on this pull request title.

Second, this change will require a change in the docs too, so people can know that the plugin uses the identifierForVendor for the UUID, what is it, and it's peculiarities. The whole iOS Quirks section should be changed to document this

**Comment by cjpearson** [comment]
I think you might still want to check in user defaults first, so the uuid value doesn't change for users who already had the app installed.

**Comment by tenfef** [comment]
I have made the adjustments above to the documentation and also restored the use of NSUserDefaults to maintain backwards compatibility.
Jira issue is here: https://issues.apache.org/jira/browse/CB-9386

**Comment by jcesarmobile** [comment]
I think you should add to the readme that users with the app installed will get the previous stored UUID instead of the identifierForVendor

**Comment by tenfef** [comment]
Have made said changes to documentation. https://github.com/apache/cordova-plugin-device/pull/36/files#diff-04c6e90faac2675aa89e2176d2eec7d8R173

**Pull request merged**
