### PR TITLE
add is_simulator for iOS & Android device

### PR DESCRIPTION
**Pull request by AndyChenW**

### CODE REVIEW

**Comment by AndyChenW** [comment]
hello, any response to pr?

**Comment by purplecabbage** [comment]
This looks good, I will look at adding it to windows+wp8
Please change the new property to `isSimulator` instead of `is_simulator`.

**Comment by AndyChenW** [comment]
a new pr is created for isSimulator.

**Comment by AndyChenW** [comment]
https://github.com/apache/cordova-plugin-device/pull/35

**Pull request closed without merging**
