### PR TITLE
add isSimulator for iOS & Android device

### PR DESCRIPTION
**Pull request by AndyChenW**
@purplecabbage change pr and property name to isSimulator.

### CODE REVIEW

**Comment by TimBarham** [comment]
Should this be "Emulator" rather than "Simulator" (that's the terminology used elsewhere in Cordova, isn't it? And the typical terminology for Android and Windows at least)?

**Comment by purplecabbage** [comment]
Attempting to avoid a semantics argument, I chose to overlook this. 
do we really need to add 2 properties? iOS simulator IS a simulator.

**Comment by purplecabbage** [comment]
2 other 'offers'
    device.isVirtual
Or the opposite
    device.isDevice

**Comment by TimBarham** [comment]
Heh, I wasn't wanting to start a semantics argument, just after consistency.

My understanding is that the usual terminology is "simulator" for iOS and "emulator" for Android and Windows. But we don't want to have two properties or different properties for different platforms.

My point was all about being internally consistent: our command to run an app on an emulator/simulator is `cordova emulate`, so to be internally consistent I'd expect the property to be `isEmulator` rather than `isSimulator`.

**Comment by purplecabbage** [comment]
Ah, gotcha. 
I actually think I like isVirtual better as it sidesteps all the sim/emu  discussions. 
I'll let this pr sit for a bit and see if we get any more opinions.

**Comment by AndyChenW** [comment]
device.isVirtual +1

**Comment by purplecabbage** [comment]
Created an issue for this here: CB-9847
Moving forward with `isVirtual`

**Comment by TimBarham** [comment]
Works for me.

**Comment by nikhilkh** [comment]
@alsorokin Isn't this what you needed for disabling failing tests on iOS simulator?

**Comment by alsorokin** [comment]
@nikhilkh this is essentially what I needed so I will use this to pend unsupported tests on iOS simulator
I guess this will add a cordova-plugin-device dependency to test plugin though

**Comment by purplecabbage** [comment]
Yes. Except it is only useful for plugins that depends on device. Accelerometer should not depend on device. I would like to move this directly into platforms, another discussion...

**Comment by alsorokin** [comment]
@purplecabbage what if we add device dependency not to accelerometer plugin itself but to tests/plugin.xml ?

**Comment by purplecabbage** [comment]
Love it!
Shockingly, @stevengill and I had this idea also.

**Comment by stevengill** [comment]
Haha we were just chatting about this yesterday. Makes most sense to add the dependency to tests/plugin.xml

**Pull request merged**
