### PR TITLE
chore: edit package.json license to match SPDX id

### PR DESCRIPTION
**Pull request by t1st3**
See [NPM package.json spec for licenses](https://docs.npmjs.com/files/package.json#license) and [SPDX license IDs](https://spdx.org/licenses/)

### CODE REVIEW

**Comment by t1st3** [comment]
just read CONTRIBUTING.md (after the contribution, sorry for that), and signed the ICLA.

**Comment by t1st3** [comment]
@asfgit You you want the same PR on other repos for Cordova plugins (splashscreen, whitelist, ...) and/or for platforms?

**Comment by purplecabbage** [comment]
Sure, if you can!

**Comment by t1st3** [comment]
@purplecabbage Sure I can, but little by little (too many non-code PRs make developer crazy!)

**Pull request merged**
