### PR TITLE
feat: Add GSFID (Google Service Framework ID) Feature

### PR DESCRIPTION
**Pull request by pankajPizone**
### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by pankajPizone** [comment]
Add GSFID Feature

**Comment by janpio** [comment]
Context: 

> The Google Services Framework Identifier (GSF ID) is a unique 16 character hexadecimal number that your device automatically requests from Google as soon as you log to your Google Account for the first time. For a specific device, the GSF ID will change only after a factory reset.

https://bytefreaks.net/android/android-get-gsf-id-google-services-framework-identifier

**Comment by janpio** [comment]
What is the use case? Why should this Android specific value be added to the plugin?

As this is Android only by definition, it could probably make sense to make this into a tiny one feature plugin.

**Comment by janpio** [comment]
CI, please rerun tests.

**Comment by erisu** [comment]
Since this PR is over three years old and failing CI back then, I will be closing this PR.

From additional research, it appears that this PR would also require an additional permission setting to be enabled.

I believe an external plugin should be created for this feature. The Id is more tired to a service, not device only.

**Pull request closed without merging**
