### PR TITLE
fix(android)!: access Context through webView.getContext() (CB-12623)

### PR DESCRIPTION
**Pull request by dreifachstein**
Android WebView can be created without an Activity. One use case is
to create a WebView within a Service and attach/detach it to an
Activity window on demand.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-device/pull/62/commits/7d4abf7e78aa14b3a6bfe6011271895f99de873e)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-device-pr/26/)

 66 tests run, 0 skipped, 0 failed.

**Comment by infil00p** [comment]
The CordovaWebView object is not actually an Android WebView, so this actually shouldn't be done.

**Comment by filmaj** [comment]
@infil00p should we close this?

**Comment by infil00p** [comment]
@filmaj Not sure.  I'm not sure what the reporter is trying to do here.

**Comment by janpio** [comment]
@dreifachstein, could you elaborate please?

**Comment by jcesarmobile** [comment]
Looks good to me, but you'll have to update engines in package.json and plugin.xml to require cordova-android >= 7.0.0 as this is not available in older versions
https://github.com/apache/cordova-android/commit/17906735dfe23e74cbe75394a0de3bf448233f25

And we on next plugin update should do a major bump because of the engines update

**Review by janpio — DISMISSED** [review]
Changes requested in https://github.com/apache/cordova-plugin-device/pull/62#issuecomment-414991528

**Comment by janpio** [comment]
Let the be tests.

**Review by jcesarmobile — APPROVED** [review]

**Comment by erisu** [comment]
I didn't see the engine requirement `cordova-android >= 7.0.0` being added as requested.
Will we add it after this PR is merged?

**Comment by jcesarmobile** [comment]
yeah, we can add it in a separate PR

**Pull request closed without merging**
